version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=db
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:taskdb
    restart: unless-stopped 